#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_home:
    path: /
    controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'home.html.twig'

#    controller: App\Controller\DefaultController::index
